<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="ANG-LT-2242" failures="1" tests="8" name="com.tests.LoginTests" time="58.088" errors="0" timestamp="2024-08-24T19:44:19 IST" skipped="2">
  <testcase classname="com.tests.LoginTests" name="validateSuccessfulLogin" time="8.241">
    <system-out>
      <![CDATA[The test validateSuccessfulLogin is passed]]>
    </system-out>
  </testcase> <!-- validateSuccessfulLogin -->
  <testcase classname="com.tests.LoginTests" name="validateInvalidPassword" time="5.470">
    <system-out>
      <![CDATA[The test validateInvalidPassword is passed]]>
    </system-out>
  </testcase> <!-- validateInvalidPassword -->
  <testcase classname="com.tests.LoginTests" name="validateInvalidUsername" time="8.366">
    <system-out>
      <![CDATA[The test validateInvalidUsername is passed]]>
    </system-out>
  </testcase> <!-- validateInvalidUsername -->
  <testcase classname="com.tests.LoginTests" name="validateInvalidCredentials" time="8.430">
    <system-out>
      <![CDATA[The test validateInvalidCredentials is passed]]>
    </system-out>
  </testcase> <!-- validateInvalidCredentials -->
  <testcase classname="com.tests.LoginTests" name="validateBlankInput" time="8.495">
    <system-out>
      <![CDATA[The test validateBlankInput is passed]]>
    </system-out>
  </testcase> <!-- validateBlankInput -->
  <testcase classname="com.tests.LoginTests" name="validateFailedScenario" time="8.079">
    <skipped/>
    <system-out>
      <![CDATA[The test validateFailedScenario is skipped]]>
    </system-out>
  </testcase> <!-- validateFailedScenario -->
  <testcase classname="com.tests.LoginTests" name="validateFailedScenario" time="5.585">
    <failure message="The following asserts failed:
	expected [Failed: Your username is invalid!] but found [Your username is invalid!],
	expected [Failed: Your username is invalid!] but found [Your username is invalid!],
	expected [Failed: Your username is invalid!] but found [Your username is invalid!]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Failed: Your username is invalid!] but found [Your username is invalid!],
expected [Failed: Your username is invalid!] but found [Your username is invalid!],
expected [Failed: Your username is invalid!] but found [Your username is invalid!]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at com.tests.LoginTests.validateFailedScenario(LoginTests.java:88)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
    <system-out>
      <![CDATA[The test validateFailedScenario is falied
<a title = 'Automation Test' href = C:\Users\Chitransh Shrivastav\eclipse-workspace\Assignment//Screenshot//image785508123.png>Screenshot</a>]]>
    </system-out>
  </testcase> <!-- validateFailedScenario -->
  <testcase classname="com.tests.LoginTests" name="validateFailedScenario" time="5.422">
    <skipped/>
    <system-out>
      <![CDATA[The test validateFailedScenario is skipped]]>
    </system-out>
  </testcase> <!-- validateFailedScenario -->
  <system-out>
    <![CDATA[The test validateSuccessfulLogin is passed
The test validateInvalidPassword is passed
The test validateInvalidUsername is passed
The test validateInvalidCredentials is passed
The test validateBlankInput is passed
The test validateFailedScenario is skipped
The test validateFailedScenario is skipped
The test validateFailedScenario is falied
<a title = 'Automation Test' href = C:\Users\Chitransh Shrivastav\eclipse-workspace\Assignment//Screenshot//image785508123.png>Screenshot</a>]]>
  </system-out>
</testsuite> <!-- com.tests.LoginTests -->
